name: failure_stack
description: A error handling library inspired by rust and error-stack, to prevent unpredicted errors.
version: 0.1.1
repository: https://github.com/SpeedReach/failure_stack/tree/main

environment:
  sdk: ^3.0.0




dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
